<%@ Page Language="C#" AutoEventWireup="true" CodeFile="MenuTree.aspx.cs" Inherits="MenuTree" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>导航菜单</title>
    <link href="Style/Main.css" rel="stylesheet" type="text/css" />
   <style>
   BODY
{
    SCROLLBAR-FACE-COLOR: #dfedf2;
    FONT-SIZE: 9pt;
    SCROLLBAR-HIGHLIGHT-COLOR: #ffffff;
    SCROLLBAR-SHADOW-COLOR: #f9f8f5;
    SCROLLBAR-3DLIGHT-COLOR: #B8E1F9;
    SCROLLBAR-ARROW-COLOR: #606d79;
    SCROLLBAR-TRACK-COLOR: #f9f8f5;
    FONT-FAMILY: "宋体";
    SCROLLBAR-DARKSHADOW-COLOR: #B8E1F9
}
   </style> 
</head>
<body style="background:#99ccff;">
    <form id="form1" runat="server">
        
        <table border="0" align="center" cellpadding="5" cellspacing="1"  style="width: 100%">
  
  <tr bgcolor="#0099cc" >
    <td colspan="2" style="height: 25px"><div align="center" style="color: #ffffff">
        <h4>操作菜单</h4></div></td>
  </tr>
    <tr >
        <td colspan="2" style="height: 100%">
         <asp:TreeView ID="TreeView1" runat="server" Target="MainFrame"
                        Width="100%" Height="99%" ExpandDepth="0" AutoGenerateDataBindings="False" 
                        CollapseImageUrl="~/Images/treeMinus.gif" ExpandImageUrl="~/Images/treePlus.gif" ImageSet="Events">
                        <ParentNodeStyle Font-Bold="False" />
                        <HoverNodeStyle
                            Font-Underline="False" ForeColor="Red" />
                        <SelectedNodeStyle Font-Underline="True" HorizontalPadding="0px" VerticalPadding="0px" />
                        <NodeStyle HorizontalPadding="5px" NodeSpacing="0px" VerticalPadding="0px" Font-Names="Verdana" Font-Size="8pt" ForeColor="Black" />
                    </asp:TreeView>  </td>
    </tr>
  
</table>
    </form>
</body>
</html>
